#!/bin/sh
# Set up the log location with proper permissions
mkdir -p /var/log/nginx
chown www-data:www-data /var/log/nginx

# Set up a path for it to do things with
# (stuff breaks without this)
mkdir -p /usr/share/nginx
chown www-data:www-data /usr/share/nginx

# write default configs
test -d '/etc/nginx' || mkdir -p /etc/nginx

cp "/tmp/nginx/koi-win" '/etc/nginx'
cp "/tmp/nginx/koi-utf" '/etc/nginx'
cp "/tmp/nginx/win-utf" '/etc/nginx'

test -f '/etc/nginx/mime.types' \
        || cp /tmp/nginx/mime.types '/etc/nginx'
cp /tmp/nginx/mime.types '/etc/nginx/mime.types.default'

test -f '/etc/nginx/fastcgi_params' \
        || cp /tmp/nginx/fastcgi_params '/etc/nginx'
cp /tmp/nginx/fastcgi_params \
        '/etc/nginx/fastcgi_params.default'

test -f '/etc/nginx/fastcgi.conf' \
        || cp /tmp/nginx/fastcgi.conf '/etc/nginx'
cp /tmp/nginx/fastcgi.conf '/etc/nginx/fastcgi.conf.default'

test -f '/etc/nginx/uwsgi_params' \
        || cp /tmp/nginx/uwsgi_params '/etc/nginx'
cp /tmp/nginx/uwsgi_params \
        '/etc/nginx/uwsgi_params.default'

test -f '/etc/nginx/scgi_params' \
        || cp /tmp/nginx/scgi_params '/etc/nginx'
cp /tmp/nginx/scgi_params \
        '/etc/nginx/scgi_params.default'

test -f '/etc/nginx/nginx.conf' \
        || cp /tmp/nginx/nginx.conf '/etc/nginx/nginx.conf'
cp /tmp/nginx/nginx.conf '/etc/nginx/nginx.conf.default'

# if systemctl is installed (fairly strong indicator systemd is in use), add a service unit file if it does not exist
if command -v systemctl 2>&1 >/dev/null && [ ! -f "/usr/lib/systemd/system/nginx.service" ]; then
# add systemd service file
cat <<EOL | sudo tee /lib/systemd/system/nginx.service
[Unit]
Description=NGINX with OpenSSL-dev
Documentation=http://nginx.org/en/docs/
After=network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
PIDFile=/var/run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t -c /etc/nginx/nginx.conf
ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf
ExecReload=/usr/sbin/nginx -s reload
ExecStop=/usr/bin/nginx -s stop
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOL

# enable and start nginx
sudo systemctl enable nginx.service
sudo systemctl restart nginx.service
fi
